// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6ItEvJzvIDy3SAmyqh5-LvRfQ0FUbIs',
    appId: '1:347073825941:web:d287adf0aecbc2d2de9f9c',
    messagingSenderId: '347073825941',
    projectId: 'my-notesflutter-project',
    authDomain: 'my-notesflutter-project.firebaseapp.com',
    storageBucket: 'my-notesflutter-project.appspot.com',
    measurementId: 'G-42FB6QYP4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdPrSQoEtT6KlEEOtfBxxnuPUkewHjWg',
    appId: '1:347073825941:android:cb0fffadf20d79e1de9f9c',
    messagingSenderId: '347073825941',
    projectId: 'my-notesflutter-project',
    storageBucket: 'my-notesflutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxhnlVBudO8dXO8OBtNj8pVNWDLANHRw',
    appId: '1:347073825941:ios:32a91882652790fade9f9c',
    messagingSenderId: '347073825941',
    projectId: 'my-notesflutter-project',
    storageBucket: 'my-notesflutter-project.appspot.com',
    iosClientId: '347073825941-umeudqrjtirbbuneghdovnpe87kfmoke.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxhnlVBudO8dXO8OBtNj8pVNWDLANHRw',
    appId: '1:347073825941:ios:32a91882652790fade9f9c',
    messagingSenderId: '347073825941',
    projectId: 'my-notesflutter-project',
    storageBucket: 'my-notesflutter-project.appspot.com',
    iosClientId: '347073825941-umeudqrjtirbbuneghdovnpe87kfmoke.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
